### ISSUE TITLE
Error when installing in Wordpress

### ISSUE THREAD

**Issue by ekazda** [htmlburger/carbon-fields-plugin#10]
Fatal error: Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found in /www/wp-content/plugins/carbon-fields-plugin-3.6.3/carbon-fields-plugin.php:25 Stack trace: #0 /wordpress/wp-includes/class-wp-hook.php(324): carbon_fields_boot_plugin('') #1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /wordpress/wp-settings.php(624): do_action('after_setup_the...') #4 /www/wp-config.php(110): require_once('/wordpress/wp-s...') #5 /wordpress/wp-config.php(5): require('/www/wp-config....') #6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...') #7 /wordpress/wp-admin/admin.php(34): require_once('/wordpress/wp-l...') #8 /wordpress/wp-admin/plugins.php(10): require_once('/wordpress/wp-a...') #9 {main} thrown in /www/wp-content/plugins/carbon-fields-plugin-3.6.3/carbon-fields-plugin.php on line 25

Wordpress Version 6.4.3

**Comment by imhvost** [comment]
+1
I have the same error.
